"""ComfyUI-shaped layout on a persistent Modal Volume.

The models Volume is Modal's own storage. Its directory names match ComfyUI's
``models/<category>/`` folders, so ``extra_model_paths.yaml`` can map them 1:1:

    /mnt/comfy-storage/vae/ae.safetensors
    /mnt/comfy-storage/text_encoders/qwen_3_4b.safetensors
    /mnt/comfy-storage/diffusion_models/z_image_bf16.safetensors

CPU hydrate writes here once. GPU containers only mount and read.
"""

from __future__ import annotations

from pathlib import Path

from recipes import MODEL_DIRS

DEFAULT_STORAGE_ROOT = Path("/mnt/comfy-storage")
DEFAULT_STORAGE_VOLUME = "comfyui-ashleykza-models"


def storage_model_path(
    storage_root: str | Path,
    category: str,
    filename: str,
) -> Path:
    if category not in MODEL_DIRS:
        raise ValueError(f"Unsupported ComfyUI model category: {category!r}")
    relative = Path(filename)
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"Unsafe model filename: {filename!r}")
    return Path(storage_root) / category / relative


def legacy_model_path(
    workspace: str | Path,
    category: str,
    filename: str,
) -> Path:
    return Path(workspace) / "models" / category / filename


def resolve_model_file(
    *,
    storage_root: str | Path,
    workspace: str | Path,
    category: str,
    filename: str,
) -> Path:
    """Prefer the Modal models Volume, then the older workspace/models layout."""
    primary = storage_model_path(storage_root, category, filename)
    if primary.is_file() and primary.stat().st_size > 0:
        return primary
    legacy = legacy_model_path(workspace, category, filename)
    if legacy.is_file() and legacy.stat().st_size > 0:
        return legacy
    return primary


def ensure_storage_layout(storage_root: str | Path) -> Path:
    root = Path(storage_root)
    for category in MODEL_DIRS:
        (root / category).mkdir(parents=True, exist_ok=True)
    (root / ".state").mkdir(parents=True, exist_ok=True)
    return root


def extra_model_paths_yaml(
    *,
    storage_root: str | Path,
    workspace: str | Path,
) -> str:
    """Map the Modal Volume onto ComfyUI model folders without hiding Image models."""
    lines = [
        "# Generated by storage.py. Volume dirs match ComfyUI models/<category>/ names.",
        "modal_storage:",
        f"    base_path: {Path(storage_root)}",
        "    is_default: true",
    ]
    for name in MODEL_DIRS:
        lines.append(f"    {name}: {name}/")
    lines.extend(
        [
            "modal_workspace:",
            f"    base_path: {Path(workspace)}",
            "    is_default: false",
        ]
    )
    for name in MODEL_DIRS:
        lines.append(f"    {name}: models/{name}/")
    lines.append("    custom_nodes: custom_nodes/")
    lines.append("")
    return "\n".join(lines)
