"""Closed exception lists for Studio recipes.

New recipes stay on the happy path: official UI JSON + lock + catalog
``mode=workflow`` + overlay. Growing any set here is a product exception and
needs a reason in the PR — not a new ``queue_*.py``.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

TEST_GPU = "L40S"
INFERENCE_GPU = "RTX-PRO-6000"
FORBIDDEN_GPUS = frozenset({"T4"})

# Official UI JSON is missing nodes on the current Image. Inner graph is core.
GRAPH_MODE_IDS = frozenset({"z-image", "z-image-turbo"})

# L40S cannot hold VRAM, or quality is GPU-dependent. Everyone else tests on L40S.
NON_L40S_DEFAULT_GPU_IDS = frozenset({"flux2-dev", "trellis2"})

# Real per-workflow adapter. HTTP still goes through workflow_queue.
ALLOWED_QUEUE_SCRIPTS = frozenset({"queue_ltx25.py"})

# Hand-patched workflows that must not become Studio recipes.
OUT_OF_CATALOG_WORKFLOWS = frozenset({"examples/ltx-2.5-t2v-i2v-distilled.json"})

# Class allowlists in workflow_queue.py. Add a class once; do not add a script.
BINDER_CLASS_SETS = (
    "workflow_queue.TEXT_CLASS_TYPES",
    "workflow_queue.SCHEDULER_TYPES",
    "workflow_queue.SIZE_CLASS_TYPES",
    "workflow_queue.GUIDER_TYPES",
    "workflow_queue.SAMPLER_TYPES",
)

# CUDA / pixi Volume work is registered in runtime_hooks, keyed by lock node ids.
CUDA_VOLUME_GATE = "runtime_hooks.sparse_3d_matches"
COMFY_ENV_VOLUME_GATE = "runtime_hooks.sam3d_matches"

CATALOG_MODES = frozenset({"graph", "workflow"})
RECIPE_ID_CHARS = frozenset("abcdefghijklmnopqrstuvwxyz0123456789.-")


def catalog_mode(payload: Mapping[str, Any]) -> str:
    mode = payload.get("mode")
    if mode in CATALOG_MODES:
        return str(mode)
    return "graph" if isinstance(payload.get("graph"), dict) else "workflow"


def validate_recipe_id(recipe_id: str) -> str:
    value = str(recipe_id or "").strip()
    if not value or value != Path(value).name:
        raise ValueError(f"invalid catalog id: {recipe_id!r}")
    if value[0] in ".-" or any(char not in RECIPE_ID_CHARS for char in value):
        raise ValueError(
            f"catalog id {recipe_id!r} must be lowercase letters, digits, '.' or '-'"
        )
    return value


def enforce_recipe_gates(payload: Mapping[str, Any]) -> None:
    """Reject new graph / T4 / silent PRO-6000-default recipes."""
    recipe_id = validate_recipe_id(str(payload.get("id") or ""))
    mode = catalog_mode(payload)
    if mode == "graph" and recipe_id not in GRAPH_MODE_IDS:
        allowed = ", ".join(sorted(GRAPH_MODE_IDS))
        raise ValueError(
            f"catalog {recipe_id!r} mode=graph is gated; only {allowed} may embed "
            "an API prompt. New recipes use mode=workflow."
        )
    if mode == "workflow" and isinstance(payload.get("graph"), dict):
        raise ValueError(
            f"catalog {recipe_id!r} mode=workflow must not embed a graph; "
            "that is the Z-Image exception, not the template."
        )
    workflow = str(payload.get("workflow") or "").replace("\\", "/")
    if workflow in OUT_OF_CATALOG_WORKFLOWS:
        raise ValueError(
            f"{workflow} stays out of catalog; keep the hand patch in "
            f"{next(iter(ALLOWED_QUEUE_SCRIPTS))}"
        )
    gpu = str(payload.get("gpu") or "").strip()
    inference = str(payload.get("gpu_inference") or gpu).strip()
    choices = [str(item) for item in (payload.get("gpu_choices") or (gpu,))]
    banned = FORBIDDEN_GPUS & {gpu, inference, *choices}
    if banned:
        raise ValueError(f"catalog {recipe_id!r} must not use {sorted(banned)}")
    if inference != INFERENCE_GPU:
        raise ValueError(
            f"catalog {recipe_id!r} gpu_inference must be {INFERENCE_GPU}"
        )
    if gpu != TEST_GPU and recipe_id not in NON_L40S_DEFAULT_GPU_IDS:
        allowed = ", ".join(sorted(NON_L40S_DEFAULT_GPU_IDS))
        raise ValueError(
            f"catalog {recipe_id!r} test gpu must be {TEST_GPU} unless listed in "
            f"NON_L40S_DEFAULT_GPU_IDS ({allowed})"
        )


def queue_scripts(scripts_dir: Path) -> set[str]:
    return {path.name for path in scripts_dir.glob("queue_*.py")}


def extra_queue_scripts(scripts_dir: Path) -> set[str]:
    return queue_scripts(scripts_dir) - set(ALLOWED_QUEUE_SCRIPTS)


def input_label(item: Mapping[str, Any]) -> str:
    io = item.get("io") if isinstance(item.get("io"), dict) else {}
    images = int(io.get("images_in") or 0)
    prompt = bool(io.get("prompt"))
    kind = str(item.get("kind") or "")
    if images and prompt:
        return "上传图 + 提示词"
    if images:
        return "上传图"
    if kind == "t2v":
        return "提示词（文生视频）"
    return "提示词"


WORKFLOW_GATES_DOCS = Path(__file__).resolve().parents[1] / "docs" / "guide" / "_generated_workflow_gates.md"
GENERATED_BANNER = "<!-- Generated by python3 -m benchmarks --write. Do not edit by hand. -->"


def render_workflow_exception_table() -> str:
    """Exception table for docs/guide/workflows.md. Source is this module."""
    queue = ", ".join(f"`{name}`" for name in sorted(ALLOWED_QUEUE_SCRIPTS))
    graphs = ", ".join(f"`{name}`" for name in sorted(GRAPH_MODE_IDS))
    return "\n".join(
        [
            GENERATED_BANNER,
            "",
            "| 还要特供 | 原因 | 闸门 |",
            "|---|---|---|",
            "| 手修 `.lock.json` | 自动 resolve 扫进了用不到的权重，或不猜 URL | 脚手架打印 `unresolved` |",
            f"| `scripts/{sorted(ALLOWED_QUEUE_SCRIPTS)[0]}` 的 patch | Image 缺官方节点 | `ALLOWED_QUEUE_SCRIPTS`（{queue}） |",
            f"| Pixal3D / TRELLIS CUDA wheels | 锁里出现对应 CNR 才装到 Volume | `{CUDA_VOLUME_GATE}` |",
            "| SAM 3D comfy-env / pixi | 锁里出现 `ComfyUI-SAM3DObjects` 才装到 Volume | "
            f"`{COMFY_ENV_VOLUME_GATE}` + `comfy_env_contract` |",
            "| `catalog/*.json` | 只给 Studio 控制面填表单 | 新配方 `mode=workflow` |",
            f"| `mode=graph` 内嵌 prompt | 只有 {graphs} | `GRAPH_MODE_IDS` |",
            "",
        ]
    )


def write_workflow_exception_docs(path: Path | None = None) -> Path:
    target = path or WORKFLOW_GATES_DOCS
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_workflow_exception_table(), encoding="utf-8")
    return target


def render_studio_recipe_table(items: Iterable[Mapping[str, Any]]) -> str:
    lines = [
        "<!-- Generated by python3 -m benchmarks --write. Do not edit by hand. -->",
        "",
        "| 配方 | 测试默认 | 正式推理 | 输入 |",
        "|---|---|---|---|",
    ]
    for item in items:
        lines.append(
            "| {title} | {gpu} | {inference} | {inputs} |".format(
                title=str(item.get("title") or item.get("id") or "").replace("|", "\\|"),
                gpu=str(item.get("gpu") or ""),
                inference=str(item.get("gpu_inference") or item.get("gpu") or ""),
                inputs=input_label(item),
            )
        )
    lines.append("")
    return "\n".join(lines)
