"""Hydrate / serve / stop the GPU App using the local Modal CLI."""

from __future__ import annotations

import json
import os
import re
import shutil
import signal
import subprocess
import threading
from pathlib import Path
from typing import Any

from catalog import load_catalog, workflow_path
from studio.keys import ROOT, load_keys, subprocess_env

STATE_DIR = ROOT / ".studio"
STATE_PATH = STATE_DIR / "state.json"
CREDS_ENV = STATE_DIR / "comfyui-creds.env"
URL_RE = re.compile(r"https://[a-z0-9.-]+\.modal\.run", re.I)

_SERVE_LOCK = threading.Lock()
_SERVE_PROC: subprocess.Popen[str] | None = None


def modal_bin() -> str:
    found = shutil.which("modal", path=subprocess_env().get("PATH"))
    if found:
        return found
    fallback = Path.home() / ".local" / "bin" / "modal"
    if fallback.is_file():
        return str(fallback)
    raise FileNotFoundError("modal CLI not found on PATH")


def _run(
    args: list[str],
    *,
    env: dict[str, str],
    log: Any | None = None,
    timeout: int | None = None,
) -> subprocess.CompletedProcess[str]:
    printable = " ".join(args)
    if log:
        log(f"$ {printable}")
    result = subprocess.run(
        args,
        cwd=ROOT,
        env=env,
        check=False,
        text=True,
        capture_output=True,
        timeout=timeout,
    )
    if log:
        for stream in (result.stdout, result.stderr):
            for line in (stream or "").splitlines():
                log(line)
    if result.returncode != 0:
        err = (result.stderr or result.stdout or "").strip()
        raise RuntimeError(err[-4000:] or f"command failed: {printable}")
    return result


def current_workspace(env: dict[str, str] | None = None) -> str:
    env = env or subprocess_env()
    result = _run([modal_bin(), "profile", "current"], env=env, timeout=30)
    name = (result.stdout or "").strip()
    if not name:
        raise RuntimeError("modal profile current returned empty workspace")
    return name.splitlines()[-1].strip()


def serve_url(workspace: str, *, dev: bool = True) -> str:
    suffix = "-dev" if dev else ""
    return f"https://{workspace}--comfyui-ashleykza-cu128-ui-ui{suffix}.modal.run"


def load_state() -> dict[str, Any]:
    if not STATE_PATH.is_file():
        return {}
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def save_state(updates: dict[str, Any]) -> dict[str, Any]:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    state = load_state()
    state.update(updates)
    STATE_PATH.write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return state


def write_secret_dotenv(log: Any | None = None) -> Path:
    keys = load_keys()
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by studio for modal secret create. Gitignored.", ""]
    for key in ("HF_TOKEN", "CIVITAI_TOKEN", "GITHUB_TOKEN"):
        if keys.get(key):
            lines.append(f"{key}={keys[key]}")
    if not any(keys.get(key) for key in ("HF_TOKEN", "CIVITAI_TOKEN", "GITHUB_TOKEN")):
        if log:
            log("未配置 HF/GitHub/Civitai，跳过 secret create（沿用已有 comfyui-creds）")
        return CREDS_ENV
    CREDS_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")
    CREDS_ENV.chmod(0o600)
    env = subprocess_env(keys)
    if log:
        log("写入 Modal Secret comfyui-creds（只含 HF / GitHub / Civitai）")
    _run(
        [modal_bin(), "secret", "create", "comfyui-creds", "--from-dotenv", str(CREDS_ENV), "--force"],
        env=env,
        log=log,
        timeout=120,
    )
    return CREDS_ENV


def hydrate(recipe_id: str, log: Any | None = None) -> dict[str, Any]:
    catalog = load_catalog(recipe_id)
    workflow = workflow_path(catalog)
    env = subprocess_env()
    write_secret_dotenv(log=log)
    if log:
        log(f"hydrate {workflow.relative_to(ROOT)}")
    _run(
        [modal_bin(), "run", "hydrate_modal.py", "--workflow", str(workflow)],
        env=env,
        log=log,
        timeout=6 * 3600,
    )
    state = save_state({"catalog": recipe_id, "hydrated": True, "workflow": str(workflow)})
    return {"catalog": recipe_id, "workflow": str(workflow.relative_to(ROOT)), "state": state}


def _read_serve_output(proc: subprocess.Popen[str], log: Any | None) -> None:
    assert proc.stdout is not None
    for line in proc.stdout:
        text = line.rstrip()
        if log:
            log(text)
        match = URL_RE.search(text)
        if match:
            save_state({"base_url": match.group(0).rstrip("/")})


def start_serve(recipe_id: str, gpu: str, log: Any | None = None) -> dict[str, Any]:
    global _SERVE_PROC
    catalog = load_catalog(recipe_id)
    chosen = gpu or str(catalog.get("gpu") or "L40S")
    allowed = set(catalog.get("gpu_choices") or (chosen,))
    if chosen not in allowed:
        raise ValueError(f"gpu {chosen!r} not in {sorted(allowed)}")
    with _SERVE_LOCK:
        if _SERVE_PROC is not None and _SERVE_PROC.poll() is None:
            state = load_state()
            return {
                "already": True,
                "pid": _SERVE_PROC.pid,
                "base_url": state.get("base_url"),
                "gpu": state.get("gpu") or chosen,
            }
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        env = subprocess_env()
        env["MODAL_GPU"] = chosen
        env["COMFY_STARTUP_TIMEOUT_SECONDS"] = "900"
        proc = subprocess.Popen(
            [modal_bin(), "serve", "comfyui_modal.py"],
            cwd=ROOT,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        _SERVE_PROC = proc
        threading.Thread(
            target=_read_serve_output,
            args=(proc, log),
            name="studio-serve-log",
            daemon=True,
        ).start()
        workspace = current_workspace(env)
        guessed = serve_url(workspace, dev=True)
        save_state(
            {
                "catalog": recipe_id,
                "gpu": chosen,
                "serve_pid": proc.pid,
                "workspace": workspace,
                "base_url": guessed,
            }
        )
        if log:
            log(f"modal serve pid={proc.pid} gpu={chosen}")
            log(f"预期地址 {guessed}")
        return {
            "already": False,
            "pid": proc.pid,
            "base_url": guessed,
            "gpu": chosen,
            "workspace": workspace,
        }


def stop_serve(log: Any | None = None) -> dict[str, Any]:
    global _SERVE_PROC
    with _SERVE_LOCK:
        proc = _SERVE_PROC
        _SERVE_PROC = None
    if proc is None or proc.poll() is not None:
        state = load_state()
        pid = state.get("serve_pid")
        if pid:
            try:
                os.kill(int(pid), signal.SIGTERM)
            except (ProcessLookupError, ValueError, PermissionError):
                pass
        save_state({"serve_pid": None})
        return {"stopped": True, "pid": pid}
    if log:
        log(f"stopping modal serve pid={proc.pid}")
    proc.send_signal(signal.SIGINT)
    try:
        proc.wait(timeout=20)
    except subprocess.TimeoutExpired:
        proc.kill()
    save_state({"serve_pid": None})
    return {"stopped": True, "pid": proc.pid}


def runtime_status() -> dict[str, Any]:
    state = load_state()
    proc = _SERVE_PROC
    running = proc is not None and proc.poll() is None
    if not running:
        pid = state.get("serve_pid")
        if pid:
            try:
                os.kill(int(pid), 0)
                running = True
            except (ProcessLookupError, PermissionError, ValueError):
                running = False
    return {
        "serve_running": running,
        "base_url": state.get("base_url"),
        "gpu": state.get("gpu"),
        "catalog": state.get("catalog"),
        "hydrated": bool(state.get("hydrated")),
        "workspace": state.get("workspace"),
        "pid": state.get("serve_pid") if running else None,
    }
