"""Hydrate / deploy / stop GPU containers using the local Modal CLI.

Default is ``modal deploy``: idle 5s scaledown actually works, and snapshots
make the next cold start cheaper. ``modal serve`` is opt-in
(``STUDIO_GPU_MODE=serve``) for live GPU-process ``.py`` edits.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import signal
import subprocess
import threading
from pathlib import Path
from typing import Any

from catalog import load_catalog, workflow_path
from modal_config import ModalSettings
from studio.keys import ROOT, load_keys, subprocess_env

STATE_DIR = ROOT / ".studio"
STATE_PATH = STATE_DIR / "state.json"
CREDS_ENV = STATE_DIR / "comfyui-creds.env"
URL_RE = re.compile(r"https://[a-z0-9.-]+\.modal\.run", re.I)
GPU_MODE_ENV = "STUDIO_GPU_MODE"
DEFAULT_GPU_MODE = "deploy"
DEPLOY_STARTUP_TIMEOUT = "3600"

_SERVE_LOCK = threading.Lock()
_SERVE_PROC: subprocess.Popen[str] | None = None


def modal_bin() -> str:
    found = shutil.which("modal", path=subprocess_env().get("PATH"))
    if found:
        return found
    fallback = Path.home() / ".local" / "bin" / "modal"
    if fallback.is_file():
        return str(fallback)
    raise FileNotFoundError("modal CLI not found on PATH")


def _run(
    args: list[str],
    *,
    env: dict[str, str],
    log: Any | None = None,
    timeout: int | None = None,
) -> subprocess.CompletedProcess[str]:
    printable = " ".join(args)
    if log:
        log(f"$ {printable}")
    result = subprocess.run(
        args,
        cwd=ROOT,
        env=env,
        check=False,
        text=True,
        capture_output=True,
        timeout=timeout,
    )
    if log:
        for stream in (result.stdout, result.stderr):
            for line in (stream or "").splitlines():
                log(line)
    if result.returncode != 0:
        err = (result.stderr or result.stdout or "").strip()
        raise RuntimeError(err[-4000:] or f"command failed: {printable}")
    return result


def current_workspace(env: dict[str, str] | None = None) -> str:
    env = env or subprocess_env()
    result = _run([modal_bin(), "profile", "current"], env=env, timeout=30)
    name = (result.stdout or "").strip()
    if not name:
        raise RuntimeError("modal profile current returned empty workspace")
    return name.splitlines()[-1].strip()


def gpu_mode() -> str:
    raw = os.environ.get(GPU_MODE_ENV, DEFAULT_GPU_MODE).strip().lower()
    return "serve" if raw == "serve" else "deploy"


def gpu_settings() -> ModalSettings:
    return ModalSettings.from_env(os.environ)


def gpu_app_name() -> str:
    return gpu_settings().app_name


def serve_url(workspace: str, *, dev: bool | None = None) -> str:
    if dev is None:
        dev = gpu_mode() == "serve"
    suffix = "-dev" if dev else ""
    return f"https://{workspace}--{gpu_app_name()}-ui-ui{suffix}.modal.run"


def _first_app_url(text: str, *, prefer_prod: bool = True) -> str | None:
    found = [match.rstrip("/") for match in URL_RE.findall(text or "")]
    if not found:
        return None
    if prefer_prod:
        for url in found:
            if "-dev" not in url:
                return url
    return found[0]


def load_state() -> dict[str, Any]:
    if not STATE_PATH.is_file():
        return {}
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def save_state(updates: dict[str, Any]) -> dict[str, Any]:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    state = load_state()
    state.update(updates)
    STATE_PATH.write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return state


def write_secret_dotenv(log: Any | None = None) -> Path:
    keys = load_keys()
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by studio for modal secret create. Gitignored.", ""]
    for key in ("HF_TOKEN", "CIVITAI_TOKEN", "GITHUB_TOKEN"):
        if keys.get(key):
            lines.append(f"{key}={keys[key]}")
    if not any(keys.get(key) for key in ("HF_TOKEN", "CIVITAI_TOKEN", "GITHUB_TOKEN")):
        if log:
            log("未配置 HF/GitHub/Civitai，跳过 secret create（沿用已有 comfyui-creds）")
        return CREDS_ENV
    CREDS_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")
    CREDS_ENV.chmod(0o600)
    env = subprocess_env(keys)
    if log:
        log("写入 Modal Secret comfyui-creds（只含 HF / GitHub / Civitai）")
    _run(
        [modal_bin(), "secret", "create", "comfyui-creds", "--from-dotenv", str(CREDS_ENV), "--force"],
        env=env,
        log=log,
        timeout=120,
    )
    return CREDS_ENV


def hydrate(recipe_id: str, log: Any | None = None) -> dict[str, Any]:
    catalog = load_catalog(recipe_id)
    workflow = workflow_path(catalog)
    env = subprocess_env()
    write_secret_dotenv(log=log)
    if log:
        log(f"hydrate {workflow.relative_to(ROOT)}")
    _run(
        [modal_bin(), "run", "hydrate_modal.py", "--workflow", str(workflow)],
        env=env,
        log=log,
        timeout=6 * 3600,
    )
    state = save_state({"catalog": recipe_id, "hydrated": True, "workflow": str(workflow)})
    return {"catalog": recipe_id, "workflow": str(workflow.relative_to(ROOT)), "state": state}


def _read_serve_output(proc: subprocess.Popen[str], log: Any | None) -> None:
    assert proc.stdout is not None
    for line in proc.stdout:
        text = line.rstrip()
        if log:
            log(text)
        match = URL_RE.search(text)
        if match:
            save_state({"base_url": match.group(0).rstrip("/")})


def _container_rows(raw: str) -> list[dict[str, str]]:
    text = (raw or "").strip()
    if not text:
        return []
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return []
    if isinstance(data, dict):
        data = data.get("containers") or data.get("items") or []
    if not isinstance(data, list):
        return []
    rows: list[dict[str, str]] = []
    for item in data:
        if not isinstance(item, dict):
            continue
        lower = {str(key).lower().replace(" ", "_"): value for key, value in item.items()}
        rows.append(
            {
                "container_id": str(lower.get("container_id") or lower.get("id") or ""),
                "app_id": str(lower.get("app_id") or ""),
                "app_name": str(
                    lower.get("app_name") or lower.get("description") or ""
                ),
            }
        )
    return rows


def is_billable_gpu_app(name: str) -> bool:
    text = name.lower()
    if "hydrate" in text:
        return False
    return gpu_app_name().lower() in text


def stop_gpu_containers(log: Any | None = None) -> list[str]:
    """Stop leftover GPU containers. Do not ``modal app stop`` — keep the snapshot."""
    env = subprocess_env()
    listed = _run([modal_bin(), "container", "list", "--json"], env=env, timeout=30)
    stopped: list[str] = []
    for row in _container_rows(listed.stdout or ""):
        container_id = row["container_id"]
        if not container_id or not is_billable_gpu_app(row["app_name"]):
            continue
        if log:
            log(f"stopping leftover GPU container {container_id} ({row['app_name']})")
        try:
            _run(
                [modal_bin(), "container", "stop", container_id],
                env=env,
                log=log,
                timeout=60,
            )
        except RuntimeError as exc:
            if log:
                log(str(exc))
            continue
        stopped.append(container_id)
    return stopped


def _chosen_gpu(recipe_id: str, gpu: str) -> str:
    catalog = load_catalog(recipe_id)
    chosen = gpu or str(catalog.get("gpu") or "L40S")
    allowed = set(catalog.get("gpu_choices") or (chosen,))
    if chosen not in allowed:
        raise ValueError(f"gpu {chosen!r} not in {sorted(allowed)}")
    return chosen


def start_gpu(recipe_id: str, gpu: str, log: Any | None = None) -> dict[str, Any]:
    if gpu_mode() == "serve":
        return start_serve(recipe_id, gpu, log=log)
    return start_deploy(recipe_id, gpu, log=log)


def start_deploy(recipe_id: str, gpu: str, log: Any | None = None) -> dict[str, Any]:
    """Publish the GPU app. Containers start on the first HTTP request, not here."""
    chosen = _chosen_gpu(recipe_id, gpu)
    _stop_local_serve(log)
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    env = subprocess_env()
    env["MODAL_GPU"] = chosen
    env["COMFY_STARTUP_TIMEOUT_SECONDS"] = DEPLOY_STARTUP_TIMEOUT
    if log:
        log(f"modal deploy gpu={chosen} (GPU 要等第一次请求才起；空闲 5 秒缩到 0)")
    result = _run(
        [modal_bin(), "deploy", "comfyui_modal.py"],
        env=env,
        log=log,
        timeout=30 * 60,
    )
    workspace = current_workspace(env)
    guessed = serve_url(workspace, dev=False)
    printed = _first_app_url(f"{result.stdout or ''}\n{result.stderr or ''}")
    base_url = printed or guessed
    save_state(
        {
            "catalog": recipe_id,
            "gpu": chosen,
            "gpu_mode": "deploy",
            "serve_pid": None,
            "workspace": workspace,
            "base_url": base_url,
        }
    )
    if log:
        log(f"已部署 {base_url}")
        log("不要开着 ComfyUI 页挡缩容。队列结束会停残留容器。")
    return {
        "already": False,
        "pid": None,
        "base_url": base_url,
        "gpu": chosen,
        "workspace": workspace,
        "gpu_mode": "deploy",
    }


def start_serve(recipe_id: str, gpu: str, log: Any | None = None) -> dict[str, Any]:
    global _SERVE_PROC
    chosen = _chosen_gpu(recipe_id, gpu)
    with _SERVE_LOCK:
        if _SERVE_PROC is not None and _SERVE_PROC.poll() is None:
            state = load_state()
            return {
                "already": True,
                "pid": _SERVE_PROC.pid,
                "base_url": state.get("base_url"),
                "gpu": state.get("gpu") or chosen,
                "gpu_mode": "serve",
            }
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        env = subprocess_env()
        env["MODAL_GPU"] = chosen
        env["COMFY_STARTUP_TIMEOUT_SECONDS"] = DEPLOY_STARTUP_TIMEOUT
        proc = subprocess.Popen(
            [modal_bin(), "serve", "comfyui_modal.py"],
            cwd=ROOT,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        _SERVE_PROC = proc
        threading.Thread(
            target=_read_serve_output,
            args=(proc, log),
            name="studio-serve-log",
            daemon=True,
        ).start()
        workspace = current_workspace(env)
        guessed = serve_url(workspace, dev=True)
        save_state(
            {
                "catalog": recipe_id,
                "gpu": chosen,
                "gpu_mode": "serve",
                "serve_pid": proc.pid,
                "workspace": workspace,
                "base_url": guessed,
            }
        )
        if log:
            log(f"modal serve pid={proc.pid} gpu={chosen}（会挡住 5 秒缩容）")
            log(f"预期地址 {guessed}")
        return {
            "already": False,
            "pid": proc.pid,
            "base_url": guessed,
            "gpu": chosen,
            "workspace": workspace,
            "gpu_mode": "serve",
        }


def _stop_local_serve(log: Any | None = None) -> int | None:
    global _SERVE_PROC
    with _SERVE_LOCK:
        proc = _SERVE_PROC
        _SERVE_PROC = None
    pid = None
    if proc is not None and proc.poll() is None:
        if log:
            log(f"stopping leftover modal serve pid={proc.pid}")
        proc.send_signal(signal.SIGINT)
        try:
            proc.wait(timeout=20)
        except subprocess.TimeoutExpired:
            proc.kill()
        pid = proc.pid
    else:
        state = load_state()
        leftover = state.get("serve_pid")
        if leftover:
            try:
                os.kill(int(leftover), signal.SIGTERM)
                pid = int(leftover)
            except (ProcessLookupError, ValueError, PermissionError, TypeError):
                pass
    save_state({"serve_pid": None})
    return pid


def stop_gpu(log: Any | None = None) -> dict[str, Any]:
    """Stop leftover serve + GPU containers. Keep the deployed app (snapshot)."""
    pid = _stop_local_serve(log)
    leftover = _safe_stop_gpu_containers(log)
    return {"stopped": True, "pid": pid, "containers": leftover, "gpu_mode": gpu_mode()}


def stop_serve(log: Any | None = None) -> dict[str, Any]:
    return stop_gpu(log)


def _safe_stop_gpu_containers(log: Any | None = None) -> list[str]:
    try:
        return stop_gpu_containers(log=log)
    except (RuntimeError, FileNotFoundError, OSError) as exc:
        if log:
            log(f"GPU container cleanup failed: {exc}")
        return []


def runtime_status() -> dict[str, Any]:
    state = load_state()
    proc = _SERVE_PROC
    running = proc is not None and proc.poll() is None
    if not running:
        pid = state.get("serve_pid")
        if pid:
            try:
                os.kill(int(pid), 0)
                running = True
            except (ProcessLookupError, PermissionError, ValueError, TypeError):
                running = False
    mode = str(state.get("gpu_mode") or gpu_mode())
    return {
        "serve_running": running,
        "gpu_mode": mode,
        "deployed": mode == "deploy" and bool(state.get("base_url")),
        "base_url": state.get("base_url"),
        "gpu": state.get("gpu"),
        "catalog": state.get("catalog"),
        "hydrated": bool(state.get("hydrated")),
        "workspace": state.get("workspace"),
        "pid": state.get("serve_pid") if running else None,
    }
